<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>car form</title>
    <link rel="stylesheet" href="/bootstrap/css/reset.css">
    <link rel="stylesheet" href="/bootstrap/css/hotel.css">
    <script src="/bootstrap/js/prefixfree.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
  </head>

  <body>

    <div id="bg"></div>

<form action="<?= $this->car_form->getAction()?>" method="<?= $this->car_form->getMethod()?>">
     <?= $this->car_form->name ?> 

    <!-- -->
<script>

$(function () {
  <?php 
     foreach ($this->locations as $key => $value)
     { ?>

    $('#name').append("<option><?php echo $value['name'];?></option>");


 <?php }?>
  // echo "<script>$('#name').append( '<option>".""."</option>')
  <!--//  foreach ($this->locations as $key => $value)
  //    {
  //     echo "<script>$('#name').append( '<option>$value['name']</option>')
  //    }-->
});



</script>


    <!-- -->
     <?= $this->car_form->date_from ?>
    <center>time from</center> <?= $this->car_form->time_form_hour ?><?= $this->car_form->time_form_min ?>
    <?= $this->car_form->am_pm1 ?>
     <br>
    <?= $this->car_form->date_to ?>
     <center>time to</center><?= $this->car_form->time_to_hour ?><?= $this->car_form->time_to_min ?>
      <?= $this->car_form->am_pm2 ?>
    <br> 
    <?= $this->car_form->submit?>
  

</form> 
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

    <script src="/bootstrap/js/bootstrap-datepicker.js"></script>
<script>
  $('#date_from').val('08/04/2016');
  $('#date_to').val('09/04/2016');
	$('#date_from').datepicker('show');
  $('#date_to').datepicker('show');
</script>   
    
    
    
  </body>
</html>