<br> <br>


 

    <?php echo "<div class='container-fluid'><img class='img-rounded' src='{$this->city_img}' style='width: %100;height: 20%'></div>";?>



   
<p>

 <div id="view-content">
    <?php
    $fbsession = new Zend_Session_Namespace('facebook');
    echo "<span class='-align-left' style='color:#3c763d'>City Description : </span>".$this->city_desc;
    if(isset($_SESSION['Zend_Auth']['storage']) || isset($fbsession->username))
    {echo "<a href='/city/addpost/city_id/{$this->city_id}'>Add Your Experience In this City</a>";}
    ?>

    <?php
    echo "<br>";

    foreach ($this->paginator as $key => $val)
    {
        echo "<br>";
        echo "<span style='background-color: #c1e2b3'>{$val['title']}</span>";
        echo "<br>";
        $subPost=substr($val['content'],0,40);
        echo "<span style='color: #3c763d'></span>".$subPost."...";

        echo "<a href='/city/post/post_id/{$val["id"]}'>See more</a>";
    }
    echo $this->paginator;
    ?>

</p>
</div>


<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>

<script>

    function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv,{
            center: {lat:<?php echo $this->city_lat?>  , lng:  <?php echo $this->city_long?>},
            zoom: 11
        });
    }
</script>
  <script>$('#map').show();</script>