<?php
define('DISQUS_SECRET_KEY', '5WdfZHwqr3QooDL0bGwVo0KWibnYQ9OmrUGkYOuzhvt8ar5VZ4o78tBekzPjCelP

');
define('DISQUS_PUBLIC_KEY', 'c7to4m5c9a740ji9fTbYarZPuBf3c3s2wbaNOSNhdwcNnDc6NEqNh9X3oX2reAui
');

$data = array(
"id" => $user->id,
"username" => $user->username,
"email" => $user->email
);
function dsq_hmacsha1($data, $key) {
$blocksize=64;
$hashfunc='sha1';
if (strlen($key)>$blocksize)
$key=pack('H*', $hashfunc($key));
$key=str_pad($key,$blocksize,chr(0x00));
$ipad=str_repeat(chr(0x36),$blocksize);
$opad=str_repeat(chr(0x5c),$blocksize);
$hmac = pack(
'H*',$hashfunc(
($key^$opad).pack(
'H*',$hashfunc(
($key^$ipad).$data
)
)
)
);
return bin2hex($hmac);
}

$message = base64_encode(json_encode($data));
$timestamp = time();
$hmac = dsq_hmacsha1($message . ' ' . $timestamp, DISQUS_SECRET_KEY);
