<!DOCTYPE html>
<html>
<head>
	<title>Cities</title>
</head>
<body>
<div class="container">

<div class="page-header" align="center">
	<h2>All Cities </h2>
</div>
<div style="margin-top: 50px;"></div>
<div >
<table class="table">
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Rate</th>
		<th>Description</th>
		<th>Image</th>
		<th>Country_id</th>
		<th colspan="3">Action</th>
	</tr>

		<?php
		foreach ($this->cities as $key => $value) {
			echo "<tr>";
			echo "<td>".$value['id']."</td>";
			echo "<td>".$value['name']."</td>";
			echo "<td>".$value['rate']."</td>";
			echo "<td>".$value['description']."</td>";
			echo "<td>".$value['country_id']."</td>";
			echo "<td><img src='".$value['image']."' height='100' width='100'></td>";
			echo "<td><a class='btn btn-success' href='/city/add'>Add</a></td>";
			echo "<td><a class='btn btn-danger' href='/city/delete/eid/".$value['id']."'>Delete</a></td>";
			echo "<td><a class='btn btn-primary' href='/city/edit/eid/".$value['id']."'>Edit</a></td>";
			echo "</tr>";

		}
		
		?>

</table>
</div>
</div>
</body>
</html>