<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Green Travel</title>
    
    

    <style>
    .carousel-inner{
        height:400px;
    }
    </style>

</head>

<body id="page-top">
<div class="container">

    <div style="height:100px;"></div>
 <div class="container">
       
 <div id="myCarousel" class="carousel slide  " data-ride="carousel" >
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
    <li data-target="#myCarousel" data-slide-to="5"></li>

  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active" >
                <div class="img_container ">
                    <img src="<?= $this->countrys_rated[0]['image']?>" alt="" >
                    <a href="country/cities?cid=<?= $this->countrys_rated[0]['id']?>" class="btn btn-info btn-xl page-scroll"> Learn More > </a>
                </div>
            </div>
    
    <?php
    $i=1; foreach($this->countrys_rated as $key=>$value): 
    if (!$i){?>
        <div class="item" >
            <div class="img_container ">
                <img src="<?= $value['image']?>" alt="" >
                <a href="country/cities?cid=<?= $value['id']?>" class="btn btn-info btn-xl page-scroll"> Learn More > </a>
            </div>
        </div>             
    <?php  } $i=0; endforeach;?>
  </div>
</div>
</div>
    <!-- <section class="bg-info" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">We've got what you need!</h2>
                    <hr class="light">
                    <p class="text-faded">Start Bootstrap has everything you need to get your new website up and running in no time! All of the templates and themes on Start Bootstrap are open source, free to download, and easy to use. No strings attached!</p>
                    <a href="#" class="btn btn-default btn-xl">Get Started!</a>
                </div>
            </div>
        </div>
    </section> -->
    <div style="height:500px;"></div>

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter">
                <?php foreach($this->citys_rated as $key=>$value): ?>
                <div class="col-lg-4 col-sm-6">
                    <a href="greentravel.com/city/display?id=<?= $value['id']?>" class="portfolio-box">
                        <img src="<?= $value['image']?>" class="img-responsive" alt="" width="200" height="200">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    <?= $value['name']?>
                                </div>
                                <div class="project-name">
                                    Show City Details
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                <?php endforeach;?>
            </div>
        </div>
    </section>


    <section id="contact">

        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Let's Get In Touch!</h2>
                    <hr class="primary">
                    <p>Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
                </div>
                <div class="col-lg-4 col-lg-offset-2 text-center">
                    <i class="fa fa-phone fa-3x wow bounceIn"></i>
                    <p>123-456-6789</p>
                </div>
                <div class="col-lg-4 text-center">
                    <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                    <p><a href="mailto:your-email@your-domain.com">greentravel@travel.com</a></p>
                </div>
            </div>
        </div>
    </section>
  
<style type="text/css">
.img_container img{
    position: absolute;
    alignment-adjust: middle;
    width: 100%;
    height: 500px;
    top: 50px;
    padding:50px;
}
.img_container a{
    position: absolute;
    margin-top: 10px;
    alignment-adjust: middle;
    z-index: 100;
    right: 44%;
    top: 200px;
}

</style>
</div>
</body>

</html>
