<!DOCTYPE html>

<head>
    <!--<!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css" type="text/css">
    <!--<!-- Latest compiled and minified JavaScript -->

    <script src="/bootstrap/js/jquery-1.12.0.min.js"></script>
    <!---->
    <!--<!-- Custom Fonts -->
    <link rel="stylesheet" href="/bootstrap/css/animate.min.css" type="text/css">

    <!--<!-- Custom CSS --/bootstrap/>
    <!--<!-- jQuery -->
    <!--<!-- Custom Theme JavaScript -->
    <!---->
    <script src="/bootstrap/js/creative.js"></script>
    <script src="/bootstrap/js/jquery.js"></script>


    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">

    <script src="/bootstrap/js/jquery.min.js"></script>
    <script src="/bootstrap/js/jquery.fittext.js"></script>
    <script src="/bootstrap//js/bootstrap.min.js"></script>

    <!-- compiled and minified CSS -->
    <link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
    <!-- Optional theme -->
    <!-- Custom Fonts -->
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/bootstrap/css/creative.css" type="text/css">
    <link rel="stylesheet" href="/bootstrap/css/datepicker.css">


</head>

<?php
$countries = $this->layout()->countries;
$uri = $this->serverUrl(true);
$path = explode('/', $uri);
$fbsession = new Zend_Session_Namespace('facebook');
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
if (!isset($path[4]) or ( !empty($path[4]) and strpos($path[4], 'add') !== 0 and strpos($path[4], 'login') !== 0 and strpos($path[4], 'update') !== 0 and strpos($path[4], 'carreservation') !== 0 and strpos($path[4], 'hotelreserve') !== 0)) {
    ?>
    <div class="container-fluid">
        <div class="row">

            <nav class="navbar navbar-fixed-top" >
                <div class="navbar-header">
                    <a class=" btn navbar-brand page-scroll" href="http://greentravel.com#page-top">Green Travel</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <?php
                    if (!empty($sessionRead)) {
                        if ($sessionRead->type == 1) { //super user "admin"
                            header("Location: /user/admin");
                        } else { //normal user
                            $name = $sessionRead->username;
                            $uid = $sessionRead->id;
                            echo '<li><a href="#"> Welcome' . " " . $name . '</a>' . '</li>';
                            ?>
                            <li><a href="<?php echo $this->baseUrl() ?>/user/update"><span class="glyphicon glyphicon-user"></span> Update Profile </a>
                            </li> 
                            <li><a href="<?php echo $this->baseUrl() ?>/user/logout"><span class="glyphicon glyphicon-log-out"></span> Logout </a>
                            </li> 
                            <?php
                        }
                    } elseif (isset($fbsession->first_name) && !empty(isset($fbsession->first_name))) {
                        $name = $fbsession->first_name;
                        echo '<li><a href="#"> Welcome' . " " . $name . '</a>' . '</li>';
                        ?>
                        <li><a href="<?php echo $this->baseUrl() ?>/user/update"><span class="glyphicon glyphicon-user"></span> Update Profile </a>
                        </li>       
                        <li><a href="<?php echo $this->baseUrl() ?>/user/logout"><span class="glyphicon glyphicon-log-in"></span> Logout </a>
                        </li> 
    <?php } else {
        ?>
                        <li><a href="<?php echo $this->baseUrl() ?>/user/login"><span class="glyphicon glyphicon-log-in"></span> Login </a>
                        </li>
                        <li><a href="<?php echo $this->baseUrl() ?>/user/add"><span class="glyphicon glyphicon-log-in"></span> SignUp </a>
                        </li> 
    <?php } ?> 
                </ul>  
                <ul class="nav navbar-nav navbar-left">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle a-item" data-toggle="dropdown" style="width: 200px;  height:51px;">Destinations <span class="caret"></span></a>
                        <ul class="dropdown-menu" style="background-color: #777777; width: 200px;">
    <?php $i = 1;
    foreach ($countries as $key => $value): ?>
                                <li class="drop-item"style=" width: 200px; height:40px;" > <a class='a-item' href="/country/cities?cid=<?= $value['id'] ?>" style="background-color: #80c52e;"><?= $value['name'] ?> </a> </li>
                            <?php endforeach; ?>                        
                        </ul>
                    </li>
    <?php if (isset($name) and $path[3] == 'city'): ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bookings  <span class="caret"></span></a>

                            <ul class="dropdown-menu">
                                <li> <a href="/city/hotelreserve?id=<?= $this->layout()->city_id ?>">Hotel Reservation</a> </li>                     
                                <li> <a href="/city/carreservation?id=<?= $this->layout()->city_id ?>">Car Request</a> </li>

                            </ul>
                        </li> 
    <?php endif; ?>
                </ul>


            </nav>

        </div>
    </div>
<?php } echo $this->layout()->content; ?>

<style>
    nav{
        font-size: 18px;
        font-weight: bold;
        color: #000000;
        background-color: #777777;
        padding: 4px;
        margin-bottom: 0px;

    }
    .drop-item:hover{
        /*        background-color: #80c52e;*/

    }
    .a-item:hover,.a-item:focus{
        height: 40px;
        width: 200px;
        background-color: #80c52e;

    }
    a{
        font-family: cursive;
        font-size: 18px;
        color: #80c52e;
    }
</style>
