<!DOCTYPE html>

<head>
    <!--<!-- Latest compiled and minified CSS -->




<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-
theme.min.css" integrity="sha384-
fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
<link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
<!--<!-- Latest compiled and minified JavaScript -->

    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<!---->

<!--<!-- Custom Fonts -->
<link rel="stylesheet" href="css/animate.min.css" type="text/css">
<!--<!-- Custom CSS -->
<link rel="stylesheet" href="css/creative.css" type="text/css">
<!--<!-- jQuery -->
<!--<!-- Custom Theme JavaScript -->
<!---->
    <script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="js/creative.js"></script>
<script src="js/jquery.js"></script>


    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        #map {
            height: 50%;
        }

    </style>


<script src="/bootstrap/js/jquery.min.js"></script>
<script src="/bootstrap/js/jquery.easing.min.js"></script>
<script src="/bootstrap/js/jquery.fittext.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

<!-- compiled and minified CSS -->
<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">
<!-- Custom Fonts -->
<link rel="stylesheet" href="/bootstrap/css/animate.min.css" type="text/css">
<!-- Custom CSS -->
<link rel="stylesheet" href="/bootstrap/css/creative.css" type="text/css">
<link rel="stylesheet" href="/bootstrap/css/datepicker.css">

</head>
<!-- <?php
$auth = Zend_Auth::getInstance();
$storage = $auth->getStorage();
$sessionRead = $storage->read();
$fbsession = new Zend_Session_Namespace('facebook');
if (!empty($sessionRead)) {
  $name = $sessionRead->username;
  $uid = $sessionRead->id;
  echo '<li><a href="#"> Welcome'." ". $name.'</a>'.'</li>'; 
  ?>
  <li><a href="<?php echo $this->baseUrl() ?>/user/logout"><span class="glyphicon glyphicon-log-in"></span> Logout </a>
  </li> 
<?php
}
//elseif (isset($fbsession->first_name) && !empty (isset($fbsession->first_name))) {
//$name = $fbsession->first_name;
//echo '<li><a href="#"> Welcome'." ". $name.'</a>'.'</li>';
?> -->
<!--<li><a href="<\?php echo $this->baseUrl() ?>/user/fblogout"><span class="glyphicon glyphicon-log-in"></span> Logout </a>
  </li> -->
<!--<\?php }?> -->
<?php echo $this->layout()->content; ?>

