<!DOCTYPE html>
<html>
<head>
	<title>Admin Page</title>
</head>
<body>
<div class="container">
	<div class="page-header text-warning" align="center">
		<h1>Admin Page</h1>
	</div>
<div style="margin-top: 80px;"></div>

<div class="col-md-3"></div>
<div  class="col-md-6">
	<a class="btn btn-warning btn-lg btn-block" href="/country/list">Manage Countries</a><br><br><br>
	<a class="btn btn-warning btn-lg btn-block" href="/city/list">Manage Cities</a><br><br><br>
	<a class="btn btn-warning btn-lg btn-block" href="/hotel/list">Manage Hotels</a><br><br><br>
	<a class="btn btn-warning btn-lg btn-block" href="/location/list">Manage Locations</a><br><br><br>


</div>

</div>
</body>
</html>