<!DOCTYPE html>
<html>
<head>
	<title>Home Page</title>
</head>
<body>
<div class="container">
<div class = "page-header" align="center">
   
   <h1>Home Page</h1>
   <h3 style="color: green;">
   	<?php
   		$fbsession = new Zend_Session_Namespace('facebook');
   		$auth = Zend_Auth::getInstance();
		$storage = $auth->getStorage();
		$sessionRead = $storage->read();
		if (!empty($sessionRead)) {
			$name = $sessionRead->username;
			// $id = $sessionRead->id;
			// var_dump($id);exit();
			echo " * Welcome " . $name . " *";
	?>
	
	
    
	<div class="pull-right">
		<a class='btn btn-default' href='/user/logout'>Logout</a>
	</div>
	<br>
<br>

	<div class="pull-right">
		<a class='btn btn-warning' href='update/name/ <?php echo $name ?>'> update </a>
	</div>
	 <div class="pull-right">
		<a class='btn btn-warning' href='hotalinfo/name/ <?php echo $name ?>'> hotal reservation information </a>
	</div>
	 <div class="pull-right">
		<a class='btn btn-warning' href='carinfo/name/ <?php echo $name ?>'> car reservation information </a>
	</div>
	<!--facebook-->
	<?php

		}

		else if (isset($fbsession->username) && !empty (isset($fbsession->username))) {
			$name = $fbsession->username;
			echo " * Welcome " . $name . " *";
	?>
	<div class="pull-right">
		<a class='btn btn-default' href="/user/fplogout">Logout</a>
	</div>

<?php
}
?>

   </h3>
    
   
</div>

	
</div>
</body>
</html>