<!DOCTYPE html>
<html>
<head>
	<title>Login</title>
</head>
<body>
<div class="container">
<div class = "page-header" >
   
   <h1>Login Page</h1>
   
</div>
<div class="container">
	<?php
		echo "<h3 class='text-danger'>".$this->error_message."</h3>";
		echo $this->login_form;
		echo '<a class="btn btn-primary" href="' . $this->facebook_url . '"> Login with Facebook </a>';
	?>

	

</div>
</body>
</html>