<!DOCTYPE html>
<html>
<head>
	<title>Update Profile</title>
	 <script src="/bootstrap/js/prefixfree.min.js"></script>
	 

    <!-- Custom CSS -->
    <link href="/bootstrap/css/simple-sidebar.css" rel="stylesheet">
</head>
<body>
<div>
<div class="page-header">
	
	 <div id="sidebar-wrapper" class="col-sm-8">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                    	index
                    </a>
                </li>
                <li>
                    <a href="#">update profile</a>
                </li>
                <li>
                	<?php
                	$auth = Zend_Auth::getInstance();
		$storage = $auth->getStorage();
		$sessionRead = $storage->read();
		if (!empty($sessionRead)) {
			$x=$sessionRead->username;
		}
		//var_dump($x);
		?>

                    <a href="/user/carinfo/name/<?= $x;?>">car reservation info</a>
                </li>
                <li>
                    <a href="/user/hotalinfo/name/<?=$x;?>">hotal reservation info</a>
                </li>
                
            </ul>
        </div>
        <div
        class="col-sm-4"></div>
<div class="col-sm-4" >
<center><h1>Update Profile</h1></center>
	<?php
		echo $this->user_form;

	?>
</div>
</div>
<script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
  
</body>
</html>
