<!DOCTYPE html>
<html>
    <head>
        <title>Update Profile</title>
        <script src="/bootstrap/js/prefixfree.min.js"></script>
        <!-- Custom CSS -->
        <link href="/bootstrap/css/simple-sidebar.css" rel="stylesheet">
        <script>$('#map').hide();</script>
    </head>
    <body>
    <div class="container">
    
        <div style="z-index: 0;top: -60;">
            <div id="sidebar-wrapper" class="col-sm-8">
                <ul class="sidebar-nav">

                    <br>
                    <li>
                        <?php
                        $auth = Zend_Auth::getInstance();
                        $storage = $auth->getStorage();
                        $sessionRead = $storage->read();
                        if (!empty($sessionRead)) {
                            $x = $sessionRead->username;
                        }
                        ?>

                        <a href="/user/carinfo/name/<?= $x; ?>">car reservation info</a>
                    </li>
                    <hr>
                    <li>
                        <a href="/user/hotalinfo/name/<?= $x; ?>">hotal reservation info</a>
                    </li>
                    <hr>

                </ul>
            </div>
        </div>
        <div class="col-sm-4"></div>
        <div class="col-sm-4" >
        <div class="page-header" align="center">
        <h1>Update Profile</h1>
    </div>
            
            <?php
            echo $this->user_form;
            ?>
        </div>
        <!-- Menu Toggle Script -->
        </div>
    </body>
</html>
