<div style="height:50px;"></div>
<div class="bkground">
    <div class="transbox">
        <p class="text-uppercase"><?= $this->country['name'] ?></p>
    </div>     
</div>
<div style="height:50px;"></div>
<?php if (isset($this->country) && !empty($this->cities)) { ?>

    <p class="text-uppercase"><?= $this->country['name'] ?> hrrrrrrrrrrrrrrrrrrrrrrrrr</p>
    <?php foreach ($this->cities as $key => $value): ?>
        <ul class="list-group">
            <!--<td><\?= $value['id']?></td>-->
            <li class="list-group-item"><a href="/city/display?id=<?= $value['id'] ?>" ><?= $value['name'] ?></a></li>
        </ul>
    <?php endforeach; ?>
    <?php
}
else {
    ?>
    <p style="font-size:24px;font-weight: bold; padding-left: 10px; margin:20px;">No cities registered for this Country. </p>
<?php } ?> 
<style>
    div.bkground {
        background: url(<?= $this->baseUrl() . $this->country['image'] ?>) no-repeat;
        background-size: 100% 100%;
        height:300px;
        border: 2px solid black;
        margin:15px;
    }

    div.transbox {
        margin: 200px;
        background-color: rgba(0,0,0,0.8);
        width:300px;
        margin-left: 50px;
        border: 1px solid black;
        opacity: 0.6;
        filter: alpha(opacity=60); /* For IE8 and earlier */
    }

    div.transbox p {
        font-size: 24px;
        margin: 5%;
        font-weight: bold;
        color: white;
    }
    a{
        font-size: 24px;
        color: #808080;
        font-weight: bold;
        text-decoration: none;  
        display: block;


    }
    a:hover ,a:focus{
        color: white;
        text-decoration: none;
    }


    li:hover , li:focus{
        background-color: #999999;
        color: white;


    }
    body{
        background-color: #e5e5e5;
    }
</style>