<?php 
if (isset($this->cities)&&!empty($this->cities)) {?>

<table>
	<?php foreach($this->cities as $key=>$value): ?>
	<tr>	
            <!--<td><\?= $value['id']?></td>-->
            <td><?= $value['rate']?></td>
            <td><a href="city/display?id=<?= $value['id']?>" class="portfolio-box"><?= $value['name']?></a></td>
	</tr>	
	<?php endforeach;?>
</table>	

<?php }
else{
	echo "no cities registered for this site";;
}

?> 